version: '3.8'
services:
  app:
    build: src/main/resources
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Girashi1
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Girashi1
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: